<?php

define("DBDRIVER", "mysql");
define("DBHOST", "localhost");
define("DBNAME", "wimf");
define("DBUSER", "root");
define("DBPWD", "");

$listOfGender = ["Monsieur", "Madame", "Autres"];
$defaultGender = $listOfGender[0];

$listOfDifficult = [
    0=>"Facile",
    1=>"Modéré",
    2=>"Difficile"
];
$defaultDifficult = 0;

$listOfCategoriefrais = [
  "Viande"=> [
          0=>"Boeuf",
          1=>"Poulet",
          2=>"Agneau",
          3=>"Porc",
          4=>"Autres"
  ],
  "Poisson"=> [
          0=>"Thon",
          1=>"Saumon",
          2=>"Maquereau",
          3=>"Sardine",
          4=>"Cabillaud"
  ],
  "Letages"=> [   0=>"Lait",
            1=>"Creme",
          2=>"Yahourt",
          3=>"Fromage_blanc"
        ],
    "Sauces"=>  [   0=>"Ketchup",
          1=>"Mayonnaise",
          2=>"BBQ",
          3=>"Vinaigrette",
          4=>"Poivre"
        ],
  "Fromage"=> [   0=>"Tomme",
          1=>"Camembert",
          2=>"Comte",
          3=>"Reblochon",
          4=>"Roquefort"
        ]
];

$errorsOfForm = [
  0=>"Description trop courte, Merci de plus détailler",
  1=>"Difficultée incorrect",
  2=>"Nom de recette incorrect",
  3=>"Les calories ne peuvent être inférieur à 0",
  4=>"Nom de l'événement doit faire entre 4 et 50 caractères",
  5=>"Nom de thème doit faire entre 4 et 30 caractères",
  6=>"Le nombre de participant doit être supérieur à 2",
  7=>"Format de date invalide"
];


$errorsSignup = [
  0=>"Tentative de hack",
  1=>"Le genre n'est pas correct",
  2=>"Le prénom doit faire plus de 2 caractères",
  3=>"Le nom doit faire plus de 2 caractères",
  4=>"L'email n'est pas valide",
  5=>"Le format de la date d'anniversaire n'est pas correct",
  7=>"La date d'anniversaire n'existe pas",
  6=>"Vous devez avoir entre 18 et 100 ans",
  8=>"Le pays n'est pas correct",
  9=>"Le mot de passe doit faire entre 8 et 20 caractères.",
  10=>"Le mot de passe de confirmation ne correspond pas",
  11=>"Le captcha est incorrect.",
  12=>"Vous devez accepter les CGU pour vous inscrire.",
  13=>"Votre numéro d'adresse doit contenir un chiffre.",
  14=>"Adresse incorrecte, 5 caractères minimum.",
  15=>"Code Postal incorrect, 5 chiffres requis.",
  16=>"Nom de ville incorrect, pas de chiffre.",
  17=>"Merci de remplir tous les champs concernant votre adresse si vous souhaitez la renseigner.",
  18=>"Votre mot de passe doit contenir au moins une minuscule, un chiffre et un caractère spécial.",
  21=>"Cette email est déjà associé à un compte.",
  22=>"Ce pseudo est déjà utilisé.",
  23=>"Le pseudo doit faire entre 4 et 25 caractères."
];

$errorsLogin = [
  0=>"Tentative de hack",
  1=>"Votre email n'existe pas. Si vous n'avez pas de compte, vous devez vous en créer un.",
  2=>"Mot de passe incorrect",
  3=>"Vous devez confirmer votre email pour vous connecter."
];

$listOfCountry = [
  "AF" => "Afghanistan",
  "AL" => "Albanie",
  "DZ" => "Algérie",
  "AS" => "Samoa",
  "AD" => "Andorre",
  "AO" => "Angola",
  "AI" => "Anguilla",
  "AQ" => "Antarctique",
  "AG" => "Barbade",
  "AR" => "Argentine",
  "AM" => "Arménie",
  "AW" => "Aruba",
  "AU" => "Australie",
  "AT" => "Autriche",
  "AZ" => "Azerbaijan",
  "BS" => "Bahamas",
  "BH" => "Bahrain",
  "BD" => "Bangladesh",
  "BB" => "Barbados",
  "BY" => "Biélorussie",
  "BE" => "Belgique",
  "BZ" => "Belize",
  "BJ" => "Benin",
  "BM" => "Bermudes",
  "BT" => "Bhoutan",
  "BO" => "Bolivie",
  "BA" => "Bosnie et Herzegovie",
  "BW" => "Botswana",
  "BR" => "Brézil",
  "BN" => "Brunei",
  "BG" => "Bulgarie",
  "BF" => "Burkina Faso",
  "BI" => "Burundi",
  "KH" => "Cambodge",
  "CM" => "Cameroun",
  "CA" => "Canada",
  "CV" => "Cap Vert",
  "KY" => "Iles Cayman",
  "CF" => "Republic Centrafricaine",
  "TD" => "Tchad",
  "CL" => "Chili",
  "CN" => "Chine",
  "CO" => "Colombie",
  "KM" => "Comores",
  "CG" => "Congo",
  "CD" => "République du Congo",
  "CR" => "Costa Rica",
  "CI" => "Cote D'Ivoire",
  "HR" => "Croatie",
  "CU" => "Cuba",
  "CY" => "Chypre",
  "CZ" => "Republique Tchèque",
  "DK" => "Danemark",
  "DJ" => "Djibouti",
  "DO" => "Republique Dominicaine",
  "EC" => "Equador",
  "EG" => "Egypte",
  "SV" => "El Salvador",
  "GQ" => "Guiné Equatoriale",
  "EE" => "Estonie",
  "ET" => "Ethiopie",
  "FJ" => "Fidji",
  "FI" => "Finlande",
  "FR" => "France",
  "GA" => "Gabon",
  "GM" => "Gambie",
  "GE" => "Georgie",
  "DE" => "Allemagne",
  "GH" => "Ghana",
  "GR" => "Grèce",
  "GD" => "Grenada",
  "GT" => "Guatemala",
  "GN" => "Guiné",
  "GW" => "Guiné-Bissau",
  "HT" => "Haiti",
  "HN" => "Honduras",
  "HK" => "Hong Kong",
  "HU" => "Hongrie",
  "IS" => "Icelande",
  "IN" => "Inde",
  "ID" => "Indonésie",
  "IR" => "Iran",
  "IQ" => "Iraq",
  "IE" => "Irelande",
  "IL" => "Israel",
  "IT" => "Italie",
  "JM" => "Jamaique",
  "JP" => "Japon",
  "JO" => "Jordanie",
  "KZ" => "Kazakhstan",
  "KE" => "Kenya",
  "KR" => "Corée du Sud",
  "KW" => "Kowait",
  "LA" => "Laos",
  "LB" => "Liban",
  "LS" => "Lesotho",
  "LR" => "Liberia",
  "LT" => "Lituanie",
  "LU" => "Luxembourg",
  "MG" => "Madagascar",
  "MY" => "Malaysie",
  "MV" => "Maldives",
  "ML" => "Mali",
  "MT" => "Malte",
  "MR" => "Mauritanie",
  "MX" => "Mexique",
  "MD" => "Moldovie",
  "MC" => "Monaco",
  "MN" => "Mongolie",
  "MA" => "Maroc",
  "MZ" => "Mozambique",
  "MM" => "Myanmar",
  "NA" => "Namibia",
  "NP" => "Nepal",
  "NL" => "Pays Bas",
  "NZ" => "Nouvelle Zélande",
  "NI" => "Nicaragua",
  "NE" => "Niger",
  "NG" => "Nigeria",
  "NO" => "Norvège",
  "OM" => "Oman",
  "PK" => "Pakistan",
  "PA" => "Panama",
  "PY" => "Paraguay",
  "PE" => "Pérou",
  "PH" => "Philipines",
  "PL" => "Pologne",
  "PT" => "Portugal",
  "PR" => "Puerto Rico",
  "QA" => "Qatar",
  "RO" => "Romanie",
  "RU" => "Russie",
  "RW" => "Rwanda",
  "SA" => "Arabie Saoudite",
  "SN" => "Sénégal",
  "SL" => "Sierra Leone",
  "SG" => "Singapoure",
  "SK" => "Slovaquie",
  "SI" => "Slovenie",
  "SO" => "Somalie",
  "ZA" => "Afrique du sud",
  "ES" => "Espagne",
  "LK" => "Sri Lanka",
  "SD" => "Siudan",
  "SR" => "Suriname",
  "SE" => "Suède",
  "CH" => "Suisse",
  "SY" => "Syrie",
  "TW" => "Taiwan",
  "TZ" => "Tanzanie",
  "TH" => "Thailand",
  "TG" => "Togo",
  "TT" => "Trinidad and Tobago",
  "TN" => "Tunisie",
  "TR" => "Turquie",
  "TM" => "Turkmenistan",
  "TV" => "Tuvalu",
  "UG" => "Ouganda",
  "UA" => "Ukraine",
  "AE" => "Emirats Arabe Unis",
  "GB" => "Royaume-Unis",
  "US" => "Etats-Unis",
  "UY" => "Uruguay",
  "UZ" => "Ouzbekistan",
  "VU" => "Vanuatu",
  "VE" => "Venezuela",
  "VN" => "Viet Nam",
  "EH" => "Sahara Occidental",
  "YE" => "Yémen",
  "ZM" => "Zambie",
  "ZW" => "Zimbabwé"
];

$errorsContact = [
  0=>"Merci de remplir tous les champs",
  1=>"Adresse mail non valide",
  2=>"Merci de rentrer un titre d'au moins 5 caractères",
  3=>"Merci de rentrer un message d'au moins 10 caractères",
];

$defaultCategoriefrais = "Viande";
$defaultOfViande = "Boeuf";
$defaultOfPoisson = "Thon";
$defaultOfLetages = "Lait";
$defaultOfSauces = "Ketchup0";
$defaultOfFromage = "Tomme";
